name: 💡 Feature request
description: Suggest a feature to improve the QuranApp
labels: [enhancement]
body:

  - type: textarea
    id: feature-description
    attributes:
      label: Describe your suggested feature
    validations:
      required: true

  - type: textarea
    id: other-details
    attributes:
      label: Other details
      placeholder: |
        Additional details and attachments.

  - type: checkboxes
    id: acknowledgements
    attributes:
      label: Acknowledgements
      description: Your request will be closed if you haven't done these steps.
      options:
        - label: I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
          required: true
        - label: I have written a short but informative title.
          required: true
